### ISSUE TITLE
Support for offline reading via slrnpull

### ISSUE THREAD

**Issue by sanel** [taviso/nntpit#6]
slrnpull [1] is a small tool that is used to pull news for offline read. Is there any way to get it working with `nntpit`?

Here is my `slrnpull.conf` sample:

```
emacs   100   0   0
linux   100   0   0
```

When I start `nntpit` with `./nntpit -D -t 3 -p 8119` and run slrnpull with `slrnpull -h localhost:8119`, I'm getting this in slrnpull output:

```
02/08/2021 19:59:05 slrnpull started.
02/08/2021 19:59:05 Reading /var/spool/slrnpull/slrnpull.conf
02/08/2021 19:59:05 Created dir /var/spool/slrnpull/news/linux.
02/08/2021 19:59:05 Connecting to host localhost ...
02/08/2021 19:59:05 Connected to host.  Posting ok.
02/08/2021 19:59:05 Fetching articles for emacs.
02/08/2021 19:59:06 ***listgroup emacs failed: Command not recognized
02/08/2021 19:59:06 Fetching articles for linux.
02/08/2021 19:59:22 ***listgroup linux failed: Command not recognized
02/08/2021 19:59:22 A total of 157 bytes received, 66 bytes sent in 17 seconds.
```

No articles were fetched.

[1] https://linux.die.net/man/1/slrnpull

**Comment by taviso** [comment]
I think `LISTGROUP` seems quite simple support, can you try it now?

**Comment by sanel** [comment]
Thank you!

It works without any problems now :)
